version: '3.8'

services:
  postgres_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres_db:5432/mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  pg_data: